#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta 0
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta 1
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta 2
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta -1
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta -2
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta 5
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cy_delta -5

CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta 10

CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta 5

CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta -5 

#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta -1
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta -2
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta 5
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 49 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/49/CHECKPOINT/model.pth" --cx_delta -5
