#CUDA_VISIBLE_DEVICES=0 python /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_single.py --exp_id 42 --epoch_id 0 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/42/CHECKPOINT/model.pth" 
#CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 42 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/42/CHECKPOINT/model.pth"
#
##
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 43 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/43/CHECKPOINT/model.pth"
#
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 43 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/43/CHECKPOINT/model.pth"

#CUDA_VISIBLE_DEVICES=1,2,3,4 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 45 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/45/CHECKPOINT/model.pth"
#CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 45 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/45/CHECKPOINT/model.pth"
CUDA_VISIBLE_DEVICES=1,2,3,4 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20230 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/inference_spdh_multi.py --exp_id 46 --epoch_id 1 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml"  --model_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/46/CHECKPOINT/model.pth"
