#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20202 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/train_spdh.py --exp_id 42 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml" --trained_spdh_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Baselines/spdh/rpe_spdh/results/results_3n_fixed_0418_oriaug_RESNET_H_dz_075_/latest_checkpoint.pth" --trained_simple_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/toy/50/CHECKPOINT/model.pth"

#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20202 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/train_spdh.py --exp_id 43 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml" --trained_spdh_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Baselines/spdh/rpe_spdh/results/results_3n_fixed_0418_oriaug_RESNET_H_dz_075_/latest_checkpoint.pth" --trained_simple_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/toy/51/CHECKPOINT/model.pth"


#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20202 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/train_spdh.py --exp_id 44 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml" --trained_spdh_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Baselines/spdh/rpe_spdh/results/results_3n_fixed_0418_oriaug_RESNET_H_dz_075_/latest_checkpoint.pth" --trained_simple_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/toy/52/CHECKPOINT/model.pth"

#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20202 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/train_spdh.py --exp_id 45 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml" --trained_spdh_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Baselines/spdh/rpe_spdh/results/results_3n_fixed_0418_oriaug_RESNET_H_dz_075_/latest_checkpoint.pth" --trained_simple_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/toy/53/CHECKPOINT/model.pth"

CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 20202 /DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/tools/train_spdh.py --exp_id 46 --cfg "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/configs/train_42_spdh_resnet_h.yaml" --trained_spdh_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Baselines/spdh/rpe_spdh/results/results_3n_fixed_0418_oriaug_RESNET_H_dz_075_/latest_checkpoint.pth" --trained_simple_net_path "/DATA/disk1/hyperplane/Depth_C2RP/Code/Ours_Code/output/toy/54/CHECKPOINT/model.pth"